name: Dependency Update

permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 * * 1" # Weekly on Monday
  workflow_call:
    inputs:
      requirements-file:
        required: false
        type: string
        default: requirements.txt

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-upgrader
      - name: Update dependencies
        run: |
          python scripts/update_dependencies.py ${{ inputs.requirements-file }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update dependencies
          title: Automated dependency update
          body: Updated dependencies in ${{ inputs.requirements-file }}
          branch: dependency-update
