name: Deploy to AWS

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      deployment-script:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      # Only specified permissions are granted - safer than write-all
      id-token: write # Required for AWS credential access
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
      - name: Run deployment script
        run: |
          ${{ inputs.deployment-script }}
