name: Performance Profile

# permissions are set at the job level if needed

on:
  workflow_call:
    inputs:
      profile-script:
        required: true
        type: string
        description: Python script to profile

jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run profiling
        run: |
          python scripts/profile_performance.py ${{ inputs.profile-script }}
