name: Python CI

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      test-command:
        required: true
        type: string
      requirements-file:
        required: false
        type: string
        default: requirements.txt

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-file }}
      - name: Run tests with coverage
        run: |
          ${{ inputs.test-command }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
