name: Python Lint

on:
  workflow_call:
    inputs:
      requirements-file:
        required: false
        type: string
        default: requirements.txt
      linter:
        required: false
        type: string
        default: flake8

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-file }}
          pip install ${{ inputs.linter }}
      - name: Run linter
        run: |
          ${{ inputs.linter }} .
