name: Security Scan

on:
  workflow_call:
    inputs:
      requirements-file:
        required: false
        type: string
        default: requirements.txt

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Snyk
        run: npm install -g snyk
      - name: Run Snyk scan
        run: |
          snyk test --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
