name: Vulnerability Scan

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: Docker image to scan
      max-concurrent-scans:
        required: false
        type: number
        default: 3
        description: Maximum concurrent scans to prevent resource overuse

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-name }}
          format: json
          output: trivy-results.json
          exit-code: 0 # Don't fail on vulnerabilities; store results
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.json
